import os
from pathlib import Path

from openai import OpenAI, OpenAIError


DEFAULT_MODEL = "openai/gpt-oss-20b"
MARKDOWN_SUFFIXES = {".md", ".markdown"}


# First version of chunking: split Markdown into paragraphs, then group
# paragraphs into roughly equal chunks according to the specified number.
# Returns a list of chunks used later by summarize_markdown
def create_markdown_chunks(markdown: str, target_chunks: int) -> list[str]:
    if target_chunks < 1:
        raise ValueError("target_chunks must be at least 1")

    paragraphs = [p.strip() for p in markdown.split("\n\n") if p.strip()]

    if not paragraphs:
        return []

    chunk_size = max(1, len(paragraphs) // target_chunks)

    chunks = []
    for index in range(0, len(paragraphs), chunk_size):
        chunks.append("\n\n".join(paragraphs[index:index + chunk_size]))

    return chunks

def summarize_markdown_chunks(chunks: list[str], max_chunk_words: int) -> str:
    if max_chunk_words < 1:
        raise ValueError("max_chunk_words must be at least 1")

    if not chunks:
        raise ValueError("input Markdown contains no content to summarize")

    client = create_ai_client()
    model = os.environ.get("DOCPIPE_MODEL", DEFAULT_MODEL)

    chunk_summaries = []
    for index, chunk in enumerate(chunks, start=1):
        print(f"Summarizing chunk {index}/{len(chunks)}...")
        chunk_summaries.append(
            summarize_single_chunk(
                client=client,
                model=model,
                chunk=chunk,
                chunk_number=index,
                total_chunks=len(chunks),
                max_summary_words=max_chunk_words,
            )
        )

    print("Merging chunk summaries...")
    return create_final_summary(
        chunk_summaries=chunk_summaries,
        max_chunk_words=max_chunk_words,
    )


def summarize_single_chunk(
    client: OpenAI,
    model: str,
    chunk: str,
    chunk_number: int,
    total_chunks: int,
    max_summary_words: int,
) -> str:
    prompt = f"""Summarize this Markdown chunk.

Chunk {chunk_number} of {total_chunks}.

Extract only information present in the text. Do not invent details.

Keep the summary under {max_summary_words} words.

Markdown chunk:

{chunk}
"""

    return call_openai(client=client, model=model, prompt=prompt)


def create_final_summary(
    chunk_summaries: list[str],
    max_chunk_words: int,
) -> str:
    chunk_label = "chunk" if len(chunk_summaries) == 1 else "chunks"
    chunk_sections = []
    for index, chunk_summary in enumerate(chunk_summaries, start=1):
        chunk_sections.append(f"### Chunk {index}\n\n{chunk_summary.strip()}")

    joined_chunk_sections = "\n\n---\n\n".join(chunk_sections)

    return f"""# Summary

## Overview

This summary was generated by summarizing {len(chunk_summaries)} {chunk_label} and merging the chunk summaries deterministically.

Each chunk summary was requested to stay under approximately {max_chunk_words} words.

## Key Points

See the chunk summaries below.

## Section-by-Section Summary

{joined_chunk_sections}
"""


def create_ai_client() -> OpenAI:
    api_key = os.environ.get("DOCPIPE_API_KEY")
    base_url = os.environ.get("DOCPIPE_BASE_URL")

    if not api_key:
        raise ValueError("DOCPIPE_API_KEY is not set")

    if base_url:
        return OpenAI(api_key=api_key, base_url=base_url)

    return OpenAI(api_key=api_key)


def call_openai(client: OpenAI, model: str, prompt: str) -> str:
    try:
        response = client.responses.create(
            model=model,
            input=prompt,
        )
    except OpenAIError as error:
        raise RuntimeError(f"OpenAI API request failed: {error}") from error

    return response.output_text.strip()


# Checks input and output path, number of pages and then 
def summarize_markdown(
    input_path: Path,
    output_path: Path,
    chunks: int,
    max_chunk_words: int,
    overwrite: bool = False) -> None:
    
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    if input_path.suffix.lower() not in MARKDOWN_SUFFIXES:
        raise ValueError(f"Input file must be Markdown: {input_path}")

    if output_path.suffix.lower() not in MARKDOWN_SUFFIXES:
        raise ValueError(f"Output file must be Markdown: {output_path}")

    if output_path.exists() and not overwrite:
        raise FileExistsError(f"Output file already exists: {output_path}")

    # Creates a markdown string from input, used with target_chunks from args to create chunks
    markdown = input_path.read_text(encoding="utf-8")
    markdown_chunks = create_markdown_chunks(
        markdown=markdown,
        target_chunks=chunks,
    )

    summary = summarize_markdown_chunks(
        chunks=markdown_chunks,
        max_chunk_words=max_chunk_words,
    )
    output_path.write_text(summary, encoding="utf-8")

    print(
        f"Wrote summary to {output_path} "
        f"using {len(markdown_chunks)} chunks."
    )
